# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Custom-Services' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Custom-Services

  target 'Custom-ServicesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Custom-ServicesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod ‘SwiftRangeSlider’
  pod 'BraintreeDropIn'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

end
